title: "Thanh Noi Phan"
description: "My personal academic website."
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"  # có thể thay bằng "dark", "air", "neon", v.v.
skin_switch: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Menu điều hướng
navigation:
  - title: "About"
    url: /about/
  - title: "CV"
    url: /cv/
  - title: "Projects"
    url: /projects/
  - title: "Research"
    url: /research/
