title: "Thanh Noi Phan"
description: "My personal academic website."
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"  # hoặc "dark"
skin_switch: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

navigation:
  - title: "Home"
    url: /
  - title: "CV"
    url: /cv/
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "Contact"
    url: /contact/
