title: Thanh-Noi Phan
email: noi.t.phan@gmail.com
description: >-
  Personal website of Thanh Noi Phan.
baseurl: ""
url: "https://thanhnoiphan.github.io"
theme: minima
markdown: kramdown

plugins:
  - jekyll-feed

# Navigation order (Left → Right)
nav:
  - title: "Home"
    url: /
  - title: "CV"
    url: /cv
  - title: "Research"
    url: /research
  - title: "Publications"
    url: /publications
  - title: "Contact"
    url: /contact
